name: Deploy notification-service

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t snsports14/notification-service .

      - name: Push Docker Image
        run: docker push snsports14/notification-service

  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Latest Docker Image
        run: docker pull snsports14/notification-service

      - name: Remove Old Container
        run: |
          if [ "$(docker ps -aq -f name=notification-service)" ]; then
            docker rm -f notification-service
          fi

      - name: Run New Docker Container
        run: |
          docker run -d -p 5004:5004 \
            --name notification-service \
            --restart unless-stopped \
            snsports14/notification-service
